/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biodataSiswa;

/**
 *
 * @author HP ZBOOK 15
 */
public class inputBio extends javax.swing.JFrame {

    /**
     * Creates new form inputBio
     */
    public inputBio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        cmbKelas = new javax.swing.JComboBox<>();
        rbTKJ = new javax.swing.JRadioButton();
        rbRPL = new javax.swing.JRadioButton();
        exit = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biodataSiswa/1657d935d4eea7b.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("BIODATA SISWA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 50, 266, 33);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 380, 120, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Nama");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 140, 120, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Absen");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 200, 120, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Kelas");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 260, 120, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Jurusan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 320, 120, 30);

        alamat.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(alamat);
        alamat.setBounds(220, 370, 270, 40);

        nama.setBackground(new java.awt.Color(204, 204, 204));
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama);
        nama.setBounds(220, 130, 270, 40);

        absen.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(absen);
        absen.setBounds(220, 190, 270, 40);

        cmbKelas.setBackground(new java.awt.Color(204, 204, 204));
        cmbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7", "X TKJ 1", "X TKJ 2", "X TKJ 3", "X TKJ 4", "X TKJ 5", "X TKJ 6" }));
        cmbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKelasActionPerformed(evt);
            }
        });
        jPanel1.add(cmbKelas);
        cmbKelas.setBounds(220, 260, 150, 30);

        rbTKJ.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbTKJ);
        rbTKJ.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbTKJ.setForeground(new java.awt.Color(153, 153, 153));
        rbTKJ.setText("TKJ");
        jPanel1.add(rbTKJ);
        rbTKJ.setBounds(340, 320, 110, 27);

        rbRPL.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbRPL);
        rbRPL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbRPL.setForeground(new java.awt.Color(153, 153, 153));
        rbRPL.setText("RPL");
        jPanel1.add(rbRPL);
        rbRPL.setBounds(220, 320, 190, 27);

        exit.setBackground(new java.awt.Color(255, 102, 0));
        exit.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("EXIT");
        exit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        exit.setBorderPainted(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(240, 600, 190, 30);

        submit.setBackground(new java.awt.Color(255, 102, 0));
        submit.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUBMIT");
        submit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        submit.setBorderPainted(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(240, 520, 190, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biodataSiswa/1657d935d4eea7b.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-440, -10, 500, 740);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biodataSiswa/1657d935d4eea7b.jpg"))); // NOI18N
        jLabel9.setText("jLabel2");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(610, 0, 100, 740);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 730);

        setBounds(0, 0, 688, 763);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKelasActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String nm,abs,jur,almt;
        String kelas = cmbKelas.getSelectedItem().toString();
        nm = nama.getText();
        abs = absen.getText();
        almt = alamat.getText();
        
        //jurusan
        if (rbRPL.isSelected()) {
            jur = "RPL";
            if (cmbKelas.getSelectedItem()=="X RPL 1") {
            }
                if (cmbKelas.getSelectedItem()=="X RPL 2"){
                }
                    if (cmbKelas.getSelectedItem()=="X RPL 3"){
                    }
                        if (cmbKelas.getSelectedItem()=="X RPL 4"){
                        }
                            if (cmbKelas.getSelectedItem()=="X RPL 5"){
                            }
                                if (cmbKelas.getSelectedItem()=="X RPL 6"){
                                }
                                    if (cmbKelas.getSelectedItem()=="X RPL 7"){
                                    }
                                    
                                    else if (rbTKJ.isSelected()){
            jur = "TKJ";
            if (cmbKelas.getSelectedItem()=="X TKJ 1"){
            }
                if (cmbKelas.getSelectedItem()=="X TKJ 2"){
                    
                }
                    if (cmbKelas.getSelectedItem()=="X TKJ 3") {
                        
                    }
                        if (cmbKelas.getSelectedItem()=="X TKJ 4"){
                            
                        }
                            if (cmbKelas.getSelectedItem()=="X TKJ 5"){
                                
                            }
                                if (cmbKelas.getSelectedItem()=="X TKJ 6"){
                                    
                                }
                                    if (cmbKelas.getSelectedItem()=="X TKJ 7"){  
                                        
                                    }                     
                                    }else {jur = "";}
            
            new outputBio(nm, abs, jur, almt, kelas).setVisible(true);
            }
    }//GEN-LAST:event_submitActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputBio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absen;
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbKelas;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton rbRPL;
    private javax.swing.JRadioButton rbTKJ;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
