/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatorStandard;

/**
 *
 * @author HP ZBOOK 15
 */
public class kalkulator extends javax.swing.JFrame {
    String angka;
    double total, bilangansatu, bilangandua;
    int pilihan;
    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
        angka="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        log = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        backspace = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        layar = new javax.swing.JTextField();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        jumlah = new javax.swing.JButton();
        plusminus1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kalkulatorStandard/blue-watercolor-brush-stroke-3-5-1024x428.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kalkulatorStandard/blue-watercolor-brush-stroke-3-5-1024x428.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kalkulatorStandard/blue-watercolor-brush-stroke-3-5-1024x428.png"))); // NOI18N
        jLabel3.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        log.setBackground(new java.awt.Color(0, 50, 78));
        log.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        log.setForeground(new java.awt.Color(255, 255, 255));
        log.setText("log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        jPanel1.add(log);
        log.setBounds(310, 290, 100, 60);

        cos.setBackground(new java.awt.Color(0, 50, 78));
        cos.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        cos.setForeground(new java.awt.Color(255, 255, 255));
        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        jPanel1.add(cos);
        cos.setBounds(110, 290, 100, 60);

        sin.setBackground(new java.awt.Color(0, 50, 78));
        sin.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        sin.setForeground(new java.awt.Color(255, 255, 255));
        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        jPanel1.add(sin);
        sin.setBounds(10, 290, 100, 60);

        tan.setBackground(new java.awt.Color(0, 50, 78));
        tan.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        tan.setForeground(new java.awt.Color(255, 255, 255));
        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        jPanel1.add(tan);
        tan.setBounds(210, 290, 100, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kalkulatorStandard/blue-watercolor-brush-stroke-3-5-1024x428.png"))); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-60, 220, 590, 140);

        hapus.setBackground(new java.awt.Color(0, 50, 78));
        hapus.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("C");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus);
        hapus.setBounds(110, 360, 100, 60);

        backspace.setBackground(new java.awt.Color(0, 50, 78));
        backspace.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        backspace.setForeground(new java.awt.Color(255, 255, 255));
        backspace.setText("←");
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });
        jPanel1.add(backspace);
        backspace.setBounds(10, 360, 100, 60);

        bagi.setBackground(new java.awt.Color(0, 50, 78));
        bagi.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        bagi.setForeground(new java.awt.Color(255, 255, 255));
        bagi.setText("÷");
        bagi.setBorder(null);
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel1.add(bagi);
        bagi.setBounds(310, 360, 100, 60);

        persen.setBackground(new java.awt.Color(0, 50, 78));
        persen.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        persen.setForeground(new java.awt.Color(255, 255, 255));
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        jPanel1.add(persen);
        persen.setBounds(210, 360, 100, 60);

        layar.setEditable(false);
        layar.setBackground(new java.awt.Color(255, 255, 255));
        layar.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        layar.setForeground(new java.awt.Color(0, 153, 255));
        layar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        layar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layarActionPerformed(evt);
            }
        });
        jPanel1.add(layar);
        layar.setBounds(10, 70, 400, 260);

        satu.setBackground(new java.awt.Color(138, 208, 255));
        satu.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        satu.setForeground(new java.awt.Color(0, 55, 92));
        satu.setText("1");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        jPanel1.add(satu);
        satu.setBounds(10, 420, 100, 60);

        dua.setBackground(new java.awt.Color(138, 208, 255));
        dua.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        dua.setForeground(new java.awt.Color(0, 55, 92));
        dua.setText("2");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        jPanel1.add(dua);
        dua.setBounds(110, 420, 100, 60);

        tiga.setBackground(new java.awt.Color(138, 208, 255));
        tiga.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        tiga.setForeground(new java.awt.Color(0, 55, 92));
        tiga.setText("3");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        jPanel1.add(tiga);
        tiga.setBounds(210, 420, 100, 60);

        kali.setBackground(new java.awt.Color(0, 50, 78));
        kali.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        kali.setForeground(new java.awt.Color(255, 255, 255));
        kali.setText("×");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        jPanel1.add(kali);
        kali.setBounds(310, 420, 100, 60);

        empat.setBackground(new java.awt.Color(138, 208, 255));
        empat.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        empat.setForeground(new java.awt.Color(0, 55, 92));
        empat.setText("4");
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        jPanel1.add(empat);
        empat.setBounds(10, 480, 100, 60);

        lima.setBackground(new java.awt.Color(138, 208, 255));
        lima.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lima.setForeground(new java.awt.Color(0, 55, 92));
        lima.setText("5");
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        jPanel1.add(lima);
        lima.setBounds(110, 480, 100, 60);

        enam.setBackground(new java.awt.Color(138, 208, 255));
        enam.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        enam.setForeground(new java.awt.Color(0, 55, 92));
        enam.setText("6");
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        jPanel1.add(enam);
        enam.setBounds(210, 480, 100, 60);

        kurang.setBackground(new java.awt.Color(0, 50, 78));
        kurang.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        kurang.setForeground(new java.awt.Color(255, 255, 255));
        kurang.setText("−");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel1.add(kurang);
        kurang.setBounds(310, 480, 100, 60);

        tujuh.setBackground(new java.awt.Color(138, 208, 255));
        tujuh.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        tujuh.setForeground(new java.awt.Color(0, 55, 92));
        tujuh.setText("7");
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        jPanel1.add(tujuh);
        tujuh.setBounds(10, 540, 100, 60);

        delapan.setBackground(new java.awt.Color(138, 208, 255));
        delapan.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        delapan.setForeground(new java.awt.Color(0, 55, 92));
        delapan.setText("8");
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        jPanel1.add(delapan);
        delapan.setBounds(110, 540, 100, 60);

        nol.setBackground(new java.awt.Color(138, 208, 255));
        nol.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        nol.setForeground(new java.awt.Color(0, 55, 92));
        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        jPanel1.add(nol);
        nol.setBounds(110, 600, 100, 60);

        sembilan.setBackground(new java.awt.Color(138, 208, 255));
        sembilan.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        sembilan.setForeground(new java.awt.Color(0, 55, 92));
        sembilan.setText("9");
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        jPanel1.add(sembilan);
        sembilan.setBounds(210, 540, 100, 60);

        tambah.setBackground(new java.awt.Color(0, 50, 78));
        tambah.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah);
        tambah.setBounds(310, 540, 100, 60);

        koma.setBackground(new java.awt.Color(0, 50, 78));
        koma.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        koma.setForeground(new java.awt.Color(255, 255, 255));
        koma.setText(".");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });
        jPanel1.add(koma);
        koma.setBounds(210, 600, 100, 60);

        jumlah.setBackground(new java.awt.Color(0, 50, 78));
        jumlah.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        jumlah.setForeground(new java.awt.Color(255, 255, 255));
        jumlah.setText("=");
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jPanel1.add(jumlah);
        jumlah.setBounds(310, 600, 100, 60);

        plusminus1.setBackground(new java.awt.Color(0, 50, 78));
        plusminus1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 22)); // NOI18N
        plusminus1.setForeground(new java.awt.Color(255, 255, 255));
        plusminus1.setText("±");
        plusminus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminus1ActionPerformed(evt);
            }
        });
        jPanel1.add(plusminus1);
        plusminus1.setBounds(10, 600, 100, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kalkulatorStandard/blue-watercolor-brush-stroke-3-5-1024x428.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-120, -120, 720, 1220);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kalkulatorStandard/blue-watercolor-brush-stroke-3-5-1024x428.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(-100, -230, 660, 1120);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kalkulatorStandard/blue-watercolor-brush-stroke-3-5-1024x428.png"))); // NOI18N
        jLabel8.setText("jLabel2");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-100, 90, 660, 1120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kalkulatorStandard/blue-watercolor-brush-stroke-3-5-1024x428.png"))); // NOI18N
        jLabel9.setText("jLabel2");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-60, 200, 660, 630);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kalkulatorStandard/blue-watercolor-brush-stroke-3-5-1024x428.png"))); // NOI18N
        jLabel10.setText("jLabel2");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-120, -440, 600, 1100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 720);

        setSize(new java.awt.Dimension(437, 712));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // TODO add your handling code here:
        bilangansatu=Double.parseDouble(angka);
            layar.setText(" Sin ");
            angka = " ";
            pilihan = 5;
        
    }//GEN-LAST:event_sinActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
        switch(pilihan){

            case 1:
            bilangandua=Double.parseDouble(angka);
            total = bilangansatu/bilangandua;
            angka = Double.toString(total);
            layar.setText(angka);
            break;
            case 2:
            bilangandua=Double.parseDouble(angka);
            total = bilangansatu+bilangandua;
            angka = Double.toString(total);
            layar.setText(angka);
            break;
            case 3:
            bilangandua=Double.parseDouble(angka);
            total = bilangansatu-bilangandua;
            angka = Double.toString(total);
            layar.setText(angka);
            break;
            case 4:
            bilangandua=Double.parseDouble(angka);
            total = bilangansatu*bilangandua;
            angka = Double.toString(total);
            layar.setText(angka);
            break;
            case 5:
            total = Math.sin(bilangansatu);
            angka = Double.toString(total);
            layar.setText(angka);
            break;
            case 6:
            total = Math.cos(bilangansatu);
            angka = Double.toString(total);
            layar.setText(angka);
            break;
            case 7:
            total = Math.tan(bilangansatu);
            angka = Double.toString(total);
            layar.setText(angka);
            break;
            case 8:
            total = bilangansatu/100;
            angka = Double.toString(total);
            layar.setText(angka);
            break;
            case 9:
            total = Math.log10(bilangansatu);
            angka = Double.toString(total);
            layar.setText(angka);
            default:
            break;
        }
    }//GEN-LAST:event_jumlahActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        bilangansatu = Double.parseDouble(angka);
        layar.setText("+");
        angka="";
        pilihan =2;
    }//GEN-LAST:event_tambahActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        // TODO add your handling code here:
        angka+="9";
        layar.setText(angka);
    }//GEN-LAST:event_sembilanActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        // TODO add your handling code here:
        angka+="0";
        layar.setText(angka);
    }//GEN-LAST:event_nolActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        // TODO add your handling code here:
        angka+="8";
        layar.setText(angka);
    }//GEN-LAST:event_delapanActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
        bilangansatu=Double.parseDouble(angka);
        layar.setText("%");
        angka="";
        pilihan=8;
    }//GEN-LAST:event_persenActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        // TODO add your handling code here:
        angka+="7";
        layar.setText(angka);
    }//GEN-LAST:event_tujuhActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        bilangansatu = Double.parseDouble(angka);
        layar.setText("-");
        angka="";
        pilihan =3;
    }//GEN-LAST:event_kurangActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        // TODO add your handling code here:
        angka+="6";
        layar.setText(angka);
    }//GEN-LAST:event_enamActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        // TODO add your handling code here:
        angka+="5";
        layar.setText(angka);
    }//GEN-LAST:event_limaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        // TODO add your handling code here:
        angka+="4";
        layar.setText(angka);
    }//GEN-LAST:event_empatActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        bilangansatu = Double.parseDouble(angka);
        layar.setText("x");
        angka="";
        pilihan = 4;
    }//GEN-LAST:event_kaliActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        // TODO add your handling code here:
        angka+="3";
        layar.setText(angka);
    }//GEN-LAST:event_tigaActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        // TODO add your handling code here:
        angka+="2";
        layar.setText(angka);
    }//GEN-LAST:event_duaActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        // TODO add your handling code here:
        
        angka+="1";
        layar.setText(angka);
    }//GEN-LAST:event_satuActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        bilangansatu = Double.parseDouble(angka);
        layar.setText("÷");
        angka="";
        pilihan = 1;

    }//GEN-LAST:event_bagiActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        layar.setText("");
        bilangansatu=0;
        bilangandua=0;
        total=0;
        angka="";
    }//GEN-LAST:event_hapusActionPerformed

    private void layarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_layarActionPerformed

    private void plusminus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminus1ActionPerformed
        // TODO add your handling code here:
        if(!angka.contains("-"))

angka = "-"+angka;

else

angka = angka.substring(1, angka.length());

layar.setText(angka);
        
    }//GEN-LAST:event_plusminus1ActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
        bilangansatu=Double.parseDouble(angka);
            layar.setText(" Log ");
            angka = " ";
            pilihan = 9;
    }//GEN-LAST:event_logActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // TODO add your handling code here:
        bilangansatu=Double.parseDouble(angka);
            layar.setText(" Cos ");
            angka = " ";
            pilihan = 6;
    }//GEN-LAST:event_cosActionPerformed

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        // TODO add your handling code here:
        angka = angka.substring(0, angka.length()-1);

layar.setText(angka);
        
    }//GEN-LAST:event_backspaceActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        // TODO add your handling code here:
        angka +=".";

layar.setText(angka+".");
    }//GEN-LAST:event_komaActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // TODO add your handling code here:
        bilangansatu=Double.parseDouble(angka);
            layar.setText(" Tan ");
            angka = " ";
            pilihan = 7;
    }//GEN-LAST:event_tanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backspace;
    private javax.swing.JButton bagi;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton cos;
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jumlah;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton kurang;
    private javax.swing.JTextField layar;
    private javax.swing.JButton lima;
    private javax.swing.JButton log;
    private javax.swing.JButton nol;
    private javax.swing.JButton persen;
    private javax.swing.JButton plusminus1;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton sin;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tan;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tujuh;
    // End of variables declaration//GEN-END:variables
}
