/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author HP ZBOOK 15
 */
public class IdealTubuh extends javax.swing.JFrame {

    /**
     * Creates new form IdealTubuh
     */
    public IdealTubuh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tinggibadan = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        beratbadan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbPerempuan = new javax.swing.JRadioButton();
        rbLaki = new javax.swing.JRadioButton();
        btKeluar = new javax.swing.JButton();
        btHitung = new javax.swing.JButton();
        btUlangi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bbIdeal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        hasilanalisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Cek Kesehatan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 60, 203, 38);

        jLabel2.setText("Jenis Kelamin");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 300, 180, 15);

        tinggibadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggibadanActionPerformed(evt);
            }
        });
        jPanel1.add(tinggibadan);
        tinggibadan.setBounds(180, 240, 130, 30);

        saran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saranActionPerformed(evt);
            }
        });
        jPanel1.add(saran);
        saran.setBounds(50, 680, 410, 30);

        jLabel3.setText("kg");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 540, 27, 15);

        beratbadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratbadanActionPerformed(evt);
            }
        });
        jPanel1.add(beratbadan);
        beratbadan.setBounds(180, 200, 130, 30);

        jLabel4.setText("Berat Badan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 210, 120, 15);

        jLabel5.setText("Tinggi Badan");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 250, 110, 15);

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");
        rbPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanActionPerformed(evt);
            }
        });
        jPanel1.add(rbPerempuan);
        rbPerempuan.setBounds(340, 300, 130, 23);

        buttonGroup1.add(rbLaki);
        rbLaki.setText("Laki - Laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });
        jPanel1.add(rbLaki);
        rbLaki.setBounds(200, 300, 110, 23);

        btKeluar.setText("Keluar");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btKeluar);
        btKeluar.setBounds(400, 400, 80, 25);

        btHitung.setText("Hitung");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btHitung);
        btHitung.setBounds(40, 400, 80, 25);

        btUlangi.setText("Ulangi");
        btUlangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUlangiActionPerformed(evt);
            }
        });
        jPanel1.add(btUlangi);
        btUlangi.setBounds(220, 400, 80, 25);

        jLabel6.setText("Nama");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 170, 70, 15);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(320, 250, 60, 15);

        jLabel8.setText("Hasil Analisa Kesehatan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 610, 200, 15);

        bbIdeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbIdealActionPerformed(evt);
            }
        });
        jPanel1.add(bbIdeal);
        bbIdeal.setBounds(300, 530, 50, 30);

        jLabel9.setText("kg");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(320, 210, 50, 15);

        jLabel10.setText("Berat badan ideal Anda adalah : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(110, 540, 260, 15);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama);
        nama.setBounds(180, 160, 220, 30);

        hasilanalisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilanalisaActionPerformed(evt);
            }
        });
        jPanel1.add(hasilanalisa);
        hasilanalisa.setBounds(50, 640, 410, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 760);

        setBounds(0, 0, 523, 794);
    }// </editor-fold>//GEN-END:initComponents

    private void tinggibadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggibadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggibadanActionPerformed

    private void saranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saranActionPerformed

    private void beratbadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratbadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratbadanActionPerformed

    private void rbPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void bbIdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbIdealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbIdealActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void hasilanalisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilanalisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilanalisaActionPerformed

    private void btUlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUlangiActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        beratbadan.setText("");
        bbIdeal.setText("");
        tinggibadan.setText("");
        saran.setText("");
        hasilanalisa.setText("");
        rbPerempuan.setSelected(false);
        rbLaki.setSelected(false);
        
    }//GEN-LAST:event_btUlangiActionPerformed

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed
        // TODO add your handling code here:
        double t, b, h = 0;
        
        //untuk mengambil nilai tinggi dengan berat serta nama
        t = Double.valueOf(tinggibadan.getText());
        b = Double.valueOf(beratbadan.getText());
        String nm = nama.getText();
        
        //pilihan jenis kelamin
        if(rbLaki.isSelected())
        {
            h = (t - 100);
        } 
        else if (rbPerempuan.isSelected())
                {
                h = (t-104);
                }
        String temp = Double.toString(h);
        
        //logika untuk analisa hasil kesehatan
        if (h < b)
        {
            bbIdeal.setText(temp);
            hasilanalisa.setText("Maaf " +nm+ ", Anda kelebihan berat badan");
            saran.setText("Atur pola makan mu dan rutinlah berolahraga ya!");
        }
        else if (h > b)
        {
            bbIdeal.setText(temp);
            hasilanalisa.setText("Hai " +nm+ ", Anda Kekurangan berat badan");
            saran.setText("Atur pola makan mu dan rutinlah berolahraga ya!");
        }
        else
        {
            bbIdeal.setText(temp);
            hasilanalisa.setText("Hai " +nm+ ", Selamat! Berat badanmu ideal!");
            saran.setText("Tetap jaga pola makan mu dengan baik ya!");
        }
    }//GEN-LAST:event_btHitungActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdealTubuh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bbIdeal;
    private javax.swing.JTextField beratbadan;
    private javax.swing.JButton btHitung;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btUlangi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasilanalisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggibadan;
    // End of variables declaration//GEN-END:variables
}
